#include "stdafx.h"

LPCTSTR MINUS = "-";
LPCTSTR AT = "@";
LPCTSTR TAB = "\t";
LPCTSTR DBNULL = "NULL";
LPCTSTR QUOTE = "'";
LPCTSTR COMMA = ",";
LPCTSTR SPACE = " ";
LPCTSTR SLASH = "/";
LPCTSTR PERCENT = "%";
LPCTSTR PERIOD = ".";
LPCTSTR EMPTYSTRING = "";
LPCTSTR NONE = "<none>";

LPCTSTR BOOKING = "BOOKING";
LPCTSTR FXBKNG = "FX-BKNG";
LPCTSTR FXMATURITY = "FXMATURITY";
LPCTSTR MATURITY = "MATURITY";
LPCTSTR TRS = "TRS";
LPCTSTR XTRS = "XTRS";
LPCTSTR Y = "Y";
LPCTSTR N = "N";
LPCTSTR B = "B";
LPCTSTR L = "L";
LPCTSTR P = "P";
LPCTSTR S = "S";
LPCTSTR F = "F";
LPCTSTR CALL = "CALL";
LPCTSTR PUT = "PUT";
LPCTSTR SECURITIES = "SECURITIES";
LPCTSTR CASH = "CASH";
LPCTSTR FOREX = "FOREX";
LPCTSTR INTSWAP = "INT. SWAP";
LPCTSTR IRS = "IRS";
LPCTSTR XIRS = "XIRS";
LPCTSTR LEVERAGE = "LEVERAGE";
LPCTSTR REPO = "REPO";
LPCTSTR SPRSWCLL = "SPR.SW.CLL";
LPCTSTR SPRSWPUT = "SPR.SW.PUT";
LPCTSTR BORROW = "BORROW";
LPCTSTR LEND = "LEND";
LPCTSTR FEES = "FEES";
LPCTSTR FUTURE = "FUTURE";
LPCTSTR CDS = "CDS";
LPCTSTR USD = "USD";

LPCTSTR CSV = "CSV";
LPCTSTR BONDTYPE = "BOND TYP(%) CAL";
LPCTSTR EQUITYTYPE = "EQUITY TYPE CAL";
LPCTSTR DBSYSDATE = "SYSDATE";
LPCTSTR TEMPLATE = "Template";
LPCTSTR TRANSNUM = "TRANS_NUM";
LPCTSTR CASHNUM = "CASH_NUM";
LPCTSTR TICKETNUM = "TICKET_NUM";
LPCTSTR PAYID = "PAY_ID";
LPCTSTR DAILYREPO = "DAILY FLOAT";
LPCTSTR DAILYREPOA = "DAILY FLOAT A";
LPCTSTR NEWASSET = "NEW ASSET";

LPCTSTR SEMAM = "SEMAM";
LPCTSTR MNGACC = "MNGACC";

BOOL BLOOMBERG_AVAILABLE = FALSE;
