#ifndef __NWIVAR_H__
#define __NWIVAR_H__

#define NOCASE			0
#define UPPERCASE		1
#define LOWERCASE		2
#define CASESENSITIVE	3

#define	WNDCTRL_UNDEFINE	0
#define WNDCTRL_EDIT		1
#define WNDCTRL_NUMEDIT		2
#define	WNDCTRL_IDEDIT		3
#define	WNDCTRL_MASKDATEEDIT	4
#define WNDCTRL_COMBOBOX	5
#define WNDCTRL_LISTBOX		6
#define WNDCTRL_CHECKBOX	7
#define WNDCTRL_GROUP		8
#define WNDCTRL_MCCOMBOBOX	9
#define WNDCTRL_STRING		10
#define WNDCTRL_MASKMINTIMEEDIT 11

extern LPCTSTR MINUS;
extern LPCTSTR AT;
extern LPCTSTR TAB;
extern LPCTSTR DBNULL;
extern LPCTSTR QUOTE;
extern LPCTSTR COMMA;
extern LPCTSTR SPACE;
extern LPCTSTR SLASH;
extern LPCTSTR PERCENT;
extern LPCTSTR PERIOD;
extern LPCTSTR EMPTYSTRING;
extern LPCTSTR NONE;

extern LPCTSTR BOOKING;
extern LPCTSTR FXBKNG;
extern LPCTSTR FXMATURITY;
extern LPCTSTR MATURITY;
extern LPCTSTR TRS;
extern LPCTSTR XTRS;
extern LPCTSTR Y;
extern LPCTSTR N;
extern LPCTSTR B;
extern LPCTSTR L;
extern LPCTSTR P;
extern LPCTSTR S;
extern LPCTSTR N;
extern LPCTSTR F;
extern LPCTSTR CALL;
extern LPCTSTR PUT;
extern LPCTSTR SECURITIES;
extern LPCTSTR CASH;
extern LPCTSTR FOREX;
extern LPCTSTR INTSWAP;
extern LPCTSTR IRS;
extern LPCTSTR XIRS;
extern LPCTSTR LEVERAGE;
extern LPCTSTR REPO;
extern LPCTSTR SPRSWCLL;
extern LPCTSTR SPRSWPUT;
extern LPCTSTR BORROW;
extern LPCTSTR LEND;
extern LPCTSTR FEES;
extern LPCTSTR FUTURE;
extern LPCTSTR CDS;
extern LPCTSTR USD;

extern LPCTSTR CSV;
extern LPCTSTR BONDTYPE;
extern LPCTSTR EQUITYTYPE;
extern LPCTSTR DBSYSDATE;
extern LPCTSTR TEMPLATE;
extern LPCTSTR TRANSNUM;
extern LPCTSTR CASHNUM;
extern LPCTSTR TICKETNUM;
extern LPCTSTR PAYID;
extern LPCTSTR DAILYREPO;
extern LPCTSTR DAILYREPOA;
extern LPCTSTR NEWASSET;

extern LPCTSTR SEMAM;
extern LPCTSTR MNGACC;

extern BOOL BLOOMBERG_AVAILABLE;
#endif